### ISSUE TITLE
nanopore minion missing in Instruments? 

### ISSUE THREAD

**Issue by colindaven** [enasequence/read_docs#13]
I would like to supply and am uploading after consulting the datasubs team Nanopore FAST5 reads as a .tar.gz.

On this page, I can't seem to find the Minion OR .tar.gz as an accepted format or sequencer.  Am I missing something or do the docs need updating ?

https://github.com/enasequence/read_docs/blob/master/reads/webin-cli.md

Thanks, 
Colin

**Comment by sholt6** [comment]
Hi Colin,
I've sent a response through our ticketing system, please let me know if you have any remaining queries.

I will update the documentation soon, but for the benefit of anyone who might stumble across this wondering the same thing:

Validation of ONT native format read files was produced for our internal processing pipeline, but was not adapted for use in Webin-CLI. This decision was made because we understand ONT to be moving toward a more standard format for reads. 
Therefore, native format and Webin-CLI are mutually exclusive: you can submit native files through the Interactive or Programmatic routes, or you can convert to FASTQ or BAM and submit through Webin-CLI. 
Sorry this wasn't made clear in our original conversation. Please

**Comment by colindaven** [comment]
Thanks for this. I would just submit BAM or FASTQ but this is a methylation project  so the FAST5 files (from 2017/2018) are needed.

So I guess the easiest way for me to proceed is using Interactive Submission to create the Project, samples etc (testing, then prod) and then Programmatic submission to upload and link the large files (2 x 200GB .tar.gz files).

Thanks again
