### ISSUE TITLE
GSC MIxS sequencing method e.g. missing Illumina, PacBio, Nanopore

### ISSUE THREAD

**Issue by peterjc** [enasequence/read_docs#15]
This query might be better raised with GSC MIxS, but how best to do that is unclear.

Quoting https://www.ebi.ac.uk/ena/submit/mixs-checklists#MIxS_shared

> # MIxS shared mandatory descriptors
> ...
> sequencing method
> Sequencing method used; e.g. Sanger, pyrosequencing, ABI-solid.

Or equivalently, quoting https://www.ebi.ac.uk/ena/data/view/ERC000014&display=xml

```xml
                    <FIELD>
                         <LABEL>sequencing method</LABEL>
                         <NAME>sequencing method</NAME>
                         <DESCRIPTION>Sequencing method used; e.g. Sanger, pyrosequencing, ABI-solid</DESCRIPTION>
                         <FIELD_TYPE>
                              <TEXT_FIELD/>
                         </FIELD_TYPE>
                         <MANDATORY>mandatory</MANDATORY>
                         <MULTIPLICITY>multiple</MULTIPLICITY>
                    </FIELD>
```

There is no controlled vocabulary given, and the most widely used technologies are not included in the example - specifically Solexa/Illumina. Also missing are PacBio and Oxford Nanopore.

How should these be recorded here?

**Comment by josieburgin** [comment]
Hi Peter, thanks for raising this issue with us.

ENA generally considers the sequencing metadata as metadata to be captured within the 'Experiment' object within ENA. Within the Experiment submission, the sequencing platform, instrument and methods used are validated against a controlled vocabulary to standardise submission. An Experiment within ENA represents the methods used for sequencing and it is the metadata from the Experiment object which is indexed and used when a user restricts a search by sequencing methods within our services.

The attribute you mention here 'sequencing method' is collected for MIxS samples so these can be compliant with the MIxS standards, however these metadata are captured in a unrestricted free-text format. This is because sequencing methods will require regular updates to stay up to date and we try to prevent updates to sample checklists unless necessary.

You can find the controlled vocabularies for Experiment submission in the Webin-CLI documentation:
https://ena-docs.readthedocs.io/en/latest/submit/reads/webin-cli.html

Best regards,
Josie
Metagenomic Bioinformatician/Software Engineer, ENA

**Comment by peterjc** [comment]
Thanks. I did think some of the GSC MIxS fields seemed redundant in the context of an ENA read submission, but that's understandable given they are used in other contexts too.

If the GSC MIxS ``sequencing method`` field is actually free text, I will probably just use "Illumina" here, or perhaps follow https://ena-docs.readthedocs.io/en/latest/submit/reads/webin-cli.html#permitted-values-for-platform
