### ISSUE TITLE
Direct users to the schema repository instead of ftp location

### ISSUE THREAD

**Issue by rabuono** [enasequence/read_docs#40]
In the ENA support guide, one can find links to the schemas being used to validate submissions like in here:
[Types of XML](https://ena-docs.readthedocs.io/en/latest/submit/general-guide/programmatic.html#types-of-xml)
[Here](https://github.com/enasequence/read_docs/blob/f1bddb1f4670810f5eec47fda6f2d35b1ebc7aba/submit/general-guide/programmatic.md?plain=1#L70) in the repo

It would be nicer if, instead of pointing to an ftp location with the schemas, the support guides would point to the files in the [enasequence/schema](https://github.com/enasequence/schema/tree/master/src/main/resources/uk/ac/ebi/ena/sra/schema) repository.

This way, the users would always be directed to the most current and in use version of the schemas.
At the time of this issue, the schemas pointed in the supporting guides are in version 1.5 while the ones that seem to be used are at version 1.11 in the repository

**Comment by josieburgin** [comment]
Hi @rabuono,

When XML Schemas are deployed into production they are always made available via the FTP so the schemas on the FTP site are the ones which are in sync with the production systems. The repository could be possibly ahead of this so I would continue to encourage users to use the schemas on the FTP.

I have updated the FTP links in the documentation so they use https protocol which means they will be easier to download now that many browsers have dropped support for ftp protocol.

Please note that we don't have formal versioning of the XSDs at the moment which is why the versioning on the repo and ftp do not align - the latest version of the XML schemas on the FTP follows the formal 1.5 version of the schema agreed with INSDC which is why these sit in version 1.5 of the FTP but not all changes are captured with this versioning system (e.g. addition of new sequencing machines).

Best wishes,
Josie

**Comment by bedroesb** [comment]
Hello @josieburgin,

I think it is quite confusing that the version of the XSDs change but that it still stays under the old 1_5 directory. This way you don't have real versioning but only the latest version. I think hosting the XSD'd on github + making use of github releases would make a lot of sense to have more transparency towards the public + to have a platform to give feedback about them. I found this repo also by googling, which will never happen with an ftp endpoint. But if it will stay ftp focused:  I do think it would be nice if there is a directory in the ftp that is not under a version folder, lets call it latest, that is in sync with the latest version directory . This would be handy for automatic pulling of the latest version of the schemas, and to link towards it in the documentation, because the url stays constant and one does not always have to update the url. 

Just some thoughts!

**Comment by rabuono** [comment]
Hi @josieburgin !

Thank you for clarifying and for updating the links.

It might be worthwhile mentioning on the [guide ](https://ena-docs.readthedocs.io/en/latest/submit/general-guide/programmatic.html#programmatic-submission)that the XSD files may be modified with no warning or version number change.

While most of the changes seem to be on expanding the XSD files, it can get cumbersome trying to understand why the webin submissions portal might be listing more accepted values for a field than my previously downloaded XSD file. Specially when there was no official version change.

**Comment by rabuono** [comment]
Original question of the issue was answered.
Closing the issue and following new topics brought up in new issues.
