### ISSUE TITLE
clarify "third party data"

### ISSUE THREAD

**Issue by liamfitzstevens** [enasequence/read_docs#76]
The [documentation](https://ena-docs.readthedocs.io/en/latest/submit/assembly/metagenome/binned.html?highlight=mags%20third%20party) states "Please contact our helpdesk if you intend to submit an assembly assembled from third party data", which I did two weeks ago and have not heard a response.

By "third party data", is the documentation referring to metagenomes from a different ENA accession (i.e., metagenomes from a previously-published study)? Or is it referring to metagenomes that are not ENA-registered?

If the former is the case, why is contacting the helpdesk necessary? It would be helpful if an explicit definition or examples of "third party data" were given in the documentation.

**Comment by alisha246** [comment]
Dear Liam,

Thank you for your query. We had responded to ticket 619141 on 27th October. Please let me know if you have not received our reply through helpdesk. Please also note that we aim to respond to all tickets within 2 weeks and based on the number of tickets, staff availability, our response may be very quick or maximum within 2 weeks.

It is necessary to contact helpdesk as these submissions need to be dealt with case by case to ensure that the third party data follows the specific policies so that the original data owners are fairly acknowledged. Also, we cannot reference third party data that is not INSDC and we will update the documentation to make this clearer. 

Best wishes,
Alisha

**Comment by liamfitzstevens** [comment]
Great. To be clear, the thing that would be great to clarify in the documentation is whether "thirty party" data means metagenomes downloaded from the ENA (but belonging to another study) or those downloaded elsewhere.

**Comment by liamfitzstevens** [comment]
Great.

To be clear, the thing that would be great to clarify in the documentation is whether "thirty party" metagenomes means those downloaded from the ENA (but belonging to another study) or those downloaded elsewhere.
